"""Bit-for-bit vector comparison against the EvidenceCore.jl oracle.

Vectors are generated by `vectors/generate_vectors.jl` (run against ParaLife's
frozen EvidenceCore.jl) — regenerate with `julia generate_vectors.jl` if the
grid changes; the committed JSON is the acceptance record.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from proofroot import (
    EVIDENCECORE_RNG_V1,
    RunPhase,
    RngBank,
    derive_stream_seed,
    is_terminal,
    parse_phase,
)

VECTORS = json.loads(
    (Path(__file__).parent.parent / "vectors" / "evidencecore_rng_v1.json").read_text()
)


@pytest.mark.parametrize("entry", VECTORS["derive_stream_seed"], ids=lambda e: f"{e['root_seed_hex']}:{e['name']}")
def test_derive_stream_seed_matches_oracle(entry):
    seed = derive_stream_seed(EVIDENCECORE_RNG_V1, int(entry["root_seed_dec"]), entry["name"])
    assert seed == int(entry["seed_dec"])
    assert f"0x{seed:016x}" == entry["seed_hex"]


@pytest.mark.parametrize("entry", VECTORS["bank_stream_seeds"], ids=lambda e: f"{e['root_seed_hex']}:{e['declared']}")
def test_bank_stream_seeds_match_oracle(entry):
    names = entry["declared"].strip("[]").split(" ")
    bank = RngBank(int(entry["root_seed_hex"], 16), names, EVIDENCECORE_RNG_V1)
    snapshot = bank.stream_seeds()
    assert {s["name"] for s in entry["streams"]} == set(snapshot)
    for stream in entry["streams"]:
        seed = snapshot[stream["name"]]
        assert seed == int(stream["seed_dec"])
        assert f"0x{seed:016x}" == stream["seed_hex"]


@pytest.mark.parametrize("entry", VECTORS["phase_terminality"], ids=lambda e: e["name"])
def test_phase_terminality_matches_oracle(entry):
    phase = parse_phase(entry["name"])
    assert is_terminal(phase) is entry["is_terminal"]
