"""Canonical serialization spec + canonicalization function (§5.9).

The 0th asset of any cross-language byte-level trace comparison is a
canonical form that does not depend on the host language's float
formatting. Rules (docs/design/proposal.md §5.9):

- **Structural layer** — the ready-made parts of RFC 8785 (JCS): object keys
  sorted, UTF-8 output, no insignificant whitespace. Key order is Unicode
  *code point* order (the proposal pins this; note RFC 8785 itself sorts by
  UTF-16 code units — the two differ only for keys mixing astral planes with
  U+E000..U+FFFF, and proofroot's spec chooses code point order).
- **Floats bypass text representation instead of praying to shortest
  round-trip**: numeric comparison fields in a trace carry the IEEE754 binary
 64 bit pattern (16-digit lowercase hex via `float_to_bits`); human-readable
  decimal may accompany as a comment field, but byte comparison only sees the
  hex. Bit patterns are identical by definition across languages.
- Consequently `canonical_bytes` **rejects raw floats** — a float that reached
  the canonicalizer would be about to be formatted by host rules, which is
  exactly the failure the spec exists to prevent. Callers pre-encode floats.

The companion vectors (`vectors/canonical_vectors.json`, regenerated by
`vectors/generate_canonical_vectors.py`) pin: key ordering incl. non-ASCII
keys, string escaping, and the classic float traps (-0.0, subnormals, NaN
payloads, infinities, 0.1).
"""

from __future__ import annotations

import json
import struct

__all__ = ["canonical_bytes", "float_to_bits", "bits_to_float"]


def float_to_bits(value: float) -> str:
    """IEEE754 binary64 bit pattern of ``value`` as '0x' + 16 lowercase hex.

    This is the *only* sanctioned float representation in comparison
    fields: -0.0, subnormals and NaN payloads round-trip exactly.
    """
    return "0x" + struct.pack(">d", value).hex()


def bits_to_float(bits: str) -> float:
    """Inverse of `float_to_bits` (accepts with or without the '0x' prefix)."""
    return struct.unpack(">d", bytes.fromhex(bits.removeprefix("0x")))[0]


def _encode(value, level_key: str | None):
    # bool before int: bool is an int subclass in Python.
    if value is None or value is True or value is False:
        return value
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        raise TypeError(
            "raw float in canonical input; pre-encode comparison fields with "
            f"float_to_bits (got {value!r}"
            + (f" at key {level_key!r}" if level_key is not None else "")
            + ")"
        )
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return [_encode(item, level_key) for item in value]
    if isinstance(value, dict):
        out = {}
        for key in sorted(value):
            if not isinstance(key, str):
                raise TypeError(f"canonical object keys must be strings, got {key!r}")
            out[key] = _encode(value[key], key)
        return out
    raise TypeError(f"value not representable in canonical form: {value!r}")


def canonical_bytes(value) -> bytes:
    """Canonical serialization: JCS structural rules, floats pre-encoded.

    Deterministic byte output for any JSON-compatible value tree whose
    numeric comparison fields already carry IEEE754 bit-pattern hex strings
    (see `float_to_bits`). Raises TypeError on raw floats, non-string keys
    and non-JSON types — those are spec violations, not formatting choices.
    """
    encoded = _encode(value, None)
    text = json.dumps(
        encoded,
        ensure_ascii=False,  # UTF-8, minimal escaping per JCS
        separators=(",", ":"),  # no insignificant whitespace
        allow_nan=False,
    )
    return text.encode("utf-8")
