#!/usr/bin/env python3
"""Regenerate vectors/canonical_vectors.json — the executable part of the
canonical serialization spec (§5.9).

Unlike the D1 vectors (generated by the Julia oracle), these are generated
from the spec's own rules: the canonical form is a new asset with no
predecessor, so the vectors pin THIS implementation's byte output as the
acceptance record. Any future second implementation (or a rewrite here) must
reproduce these bytes. Run from anywhere:  python3 generate_canonical_vectors.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from proofroot.canonical import canonical_bytes, float_to_bits, bits_to_float

OUT = Path(__file__).parent / "canonical_vectors.json"


def canonical_case(name: str, value) -> dict:
    return {
        "name": name,
        "input": value,
        "canonical_hex": canonical_bytes(value).hex(),
    }


def bits_case(decimal: str, value: float) -> dict:
    return {
        "decimal": decimal,  # comment field: human-readable only
        "bits_hex": float_to_bits(value),
        "roundtrip_decimal": repr(bits_to_float(float_to_bits(value))),
    }


def main() -> None:
    vectors = {
        "schema": "proofroot.vectors.canonical",
        "generated_by": "vectors/generate_canonical_vectors.py",
        # Structural layer: key ordering (code point order), escaping, whitespace.
        "canonical_bytes": [
            canonical_case("empty_object", {}),
            canonical_case("empty_array", []),
            canonical_case("nested_scalars", {"b": 1, "a": [None, True, False, -7], "c": "x"}),
            # Code point order: 'Z' (U+005A) < 'a' (U+0061) < 'é' (U+00E9) < '中' (U+4E2D) < '😀' (U+1F600)
            canonical_case(
                "codepoint_key_order", {"é": 2, "Z": 1, "😀": 5, "a": 3, "中": 4}
            ),
            canonical_case("unicode_strings", {"k": "café 中 😀 \" \\ \n\t\x01"}),
            canonical_case("deep_nesting", {"a": [{"b": [{"c": []}]}]}),
            canonical_case("int_boundaries", {"u64max": 18446744073709551615, "neg": -9223372036854775808}),
        ],
        # Float layer: IEEE754 bit patterns (comparison fields), the classic traps.
        "float_bits": [
            bits_case("0.0", 0.0),
            bits_case("-0.0", -0.0),  # distinct from 0.0 at the bit level
            bits_case("0.1", 0.1),  # shortest round-trip ≠ exact value
            bits_case("min_subnormal", 5e-324),
            bits_case("max_double", 1.7976931348623157e308),
            bits_case("infinity", float("inf")),
            bits_case("-infinity", float("-inf")),
            bits_case("nan_quiet_default", float("nan")),  # 0x7ff8…: payload not preserved by Python literals
            bits_case("nan_payload_1", bits_to_float("0x7ff8000000000001")),
            bits_case("nan_negative_quiet", bits_to_float("0xfff8000000000000")),
            bits_case("one_third", 1 / 3),
        ],
        # Bit-pattern identity: -0.0 vs 0.0 compare equal as floats but must
        # never collide in a byte-level comparison of traces.
        "signed_zero_distinct": {
            "zero": float_to_bits(0.0),
            "negzero": float_to_bits(-0.0),
        },
    }
    assert vectors["signed_zero_distinct"]["zero"] != vectors["signed_zero_distinct"]["negzero"]
    OUT.write_text(json.dumps(vectors, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
